databases:
  - name: budget_app
    databaseName: budget_app
    user: budget_app

services:
  - type: web
    name: budget_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app
          property: connectionString
      - key: 09c315b0b748767b107ce075bbb84a82
        sync: false
